In [5]:
import sklearn
import time
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np 
from sklearn.metrics import classification_report, confusion_matrix 
sdf=pd.read_excel(r'C:\Users\pc\Documents\Newmodelfeature\features\full\shuffle13.xlsx')
X=sdf.iloc[:,:-1]
print(X.shape)
Y=sdf.iloc[:,-1]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2,shuffle=False)
dtc=DecisionTreeClassifier(criterion='entropy',random_state=0)
start=time.time()
dtc.fit(X_train,Y_train)  
#filename='tree.sav'
stop=time.time()
print(stop-start)
result=dtc.score(X_test,Y_test)
print(result)
predictions = dtc.predict(X_test) 
print(confusion_matrix(Y_test,predictions))  
print(classification_report(Y_test,predictions))

(2665, 405)
0.7470564842224121
0.6697936210131332
[[34  4  0  0  1  0  0  0  4  0  2  0  0]
 [ 3 37  0  0  0  1  0  0  0  1  0  0  0]
 [ 0  0 39  0  0  0  0  2  0  2  0  0  0]
 [ 0  0  2 27  1  2  2  1  0  4  5  0  0]
 [ 0  0  0  3 39  1  1  0  0  1  0  0  1]
 [ 0  0  0  3  0 20  1  1  5  4  0  1  6]
 [ 0  0  0  4  0  0 20  0  0 16  5  1  1]
 [ 1  0  2  0  3  1  0 20  0  0  2  0  0]
 [ 1  0  0  0  0  7  0  0 31  0  1  2  0]
 [ 0  0  0  5  1  0  7  3  0 14  2  0  3]
 [ 2  0  1  5  1  0  4  0  3  1 22  2  1]
 [ 0  0  0  0  4  2  0  0  1  1  1 26  4]
 [ 0  0  0  4  0  0  2  2  1  0  1  0 28]]
              precision    recall  f1-score   support

           0       0.83      0.76      0.79        45
           1       0.90      0.88      0.89        42
           2       0.89      0.91      0.90        43
           3       0.53      0.61      0.57        44
           4       0.78      0.85      0.81        46
           5       0.59      0.49      0.53        41
           6       0.54 