In [12]:
import sklearn
import time
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.externals import joblib
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np 
from sklearn.metrics import classification_report, confusion_matrix 
#df = pd.read_excel (r'C:\Users\pc\Documents\Newmodelfeature\features\full\new13.xlsx')
#dfn=df.sample(frac=1)
#dfn.to_excel(r'C:\Users\pc\Documents\Newmodelfeature\features\full\shuffle13.xlsx')
sdf=pd.read_excel(r'C:\Users\pc\Documents\Newmodelfeature\features\full\shuffle13.xlsx')
#td=pd.read_excel (r'C:\Users\pc\Documents\Newmodelfeature\features\test.xlsx')
X=sdf.iloc[:,:-1]
print(X.shape)
Y=sdf.iloc[:,-1]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2,shuffle=False)
knn=KNeighborsClassifier(n_neighbors=3)
start=time.time()
knn.fit(X_train,Y_train)
stop=time.time()
print(stop-start)
result=knn.score(X_test,Y_test)
print(result)
predictions = knn.predict(X_test) 
print(confusion_matrix(Y_test,predictions))  
print(classification_report(Y_test,predictions)) 

(2665, 405)
0.31895899772644043
0.6791744840525328
[[29  1  0  2  0  0  3  0  4  1  4  1  0]
 [ 6 35  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0 37  2  1  0  2  0  0  1  0  0  0]
 [ 7  1  1 30  0  3  0  0  0  1  1  0  0]
 [ 0  0  0  4 37  0  2  0  0  0  1  2  0]
 [ 5  1  0  4  0 29  1  0  0  0  1  0  0]
 [ 6  0  0  4  1  1 31  0  0  2  0  1  1]
 [ 3  0  0  4  1  0  0 20  0  0  1  0  0]
 [ 3  0  0  0  0  2  0  0 36  1  0  0  0]
 [ 7  1  1  4  1  0  5  1  0 13  0  2  0]
 [16  4  1  4  1  0  1  0  0  1 12  1  1]
 [ 7  1  0  0  4  0  0  0  1  0  0 26  0]
 [ 6  1  0  1  0  1  0  1  0  0  1  0 27]]
              precision    recall  f1-score   support

           0       0.31      0.64      0.41        45
           1       0.78      0.83      0.80        42
           2       0.93      0.86      0.89        43
           3       0.50      0.68      0.58        44
           4       0.80      0.80      0.80        46
           5       0.81      0.71      0.75        41
           6       0.69